apiVersion: apps/v1
kind: Deployment
metadata:
  name: front_ops 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front_ops
  template:
    metadata:
      labels:
        app: front_ops
    spec:
      containers:
        - name: front_ops
          image: 192.168.1.10:8443/front_ops # 여기에서 React 프로젝트의 이미지로 변경
          #command: ["sh", "-c", "cd /099 && npm install && npm start"]
          ports:
            - containerPort: 80
